name: clearit_server
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
#  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


#  full_screen_image: ^1.0.2
#  modal_progress_hud: ^0.1.3
#  pin_entry_text_field: ^0.1.4
  #  new
  cupertino_icons: ^1.0.3
  file_picker: ^3.0.3
  firebase_storage: ^8.1.3
  image_picker: ^0.8.0+4
  shared_preferences: ^2.0.6
  modal_bottom_sheet: ^2.0.0
  timer_count_down: ^2.1.0+1
  cached_network_image: ^3.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  fluttertoast: ^8.0.7
  argon_buttons_flutter: ^1.1.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  photo_view: ^0.11.1
  flutter_pdfview: ^1.1.0
  audioplayers: ^0.19.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  country_pickers: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

