name: clearit_server
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  #  newly updated
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  image_picker: ^0.7.4
  shared_preferences: ^2.0.5
  country_pickers: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  timer_count_down: ^2.0.1
  full_screen_image: ^1.0.2
  cached_network_image: ^3.0.0
  modal_progress_hud: ^0.1.3
  auto_size_text: ^2.1.0
  fluttertoast: ^8.0.6
  argon_buttons_flutter: ^1.0.6
  provider: ^5.0.0
  pin_entry_text_field: ^0.1.4
  flutter_spinkit: ^5.0.0
  flutter_pdfview: ^1.0.1
  photo_view: ^0.11.1
  file_picker: ^3.0.2+1
  audioplayers: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

